name: deployment

on:
  push:
    branches: [main]
  
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        run: actions/checkout@v4

      - name: Set up Node
        run: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        
      - name: Build app
        run: npm run build